### ISSUE TITLE
보고서 제목 날짜 수정

### ISSUE THREAD

**Issue by LeeGeunHAHAHA** [Hanium-RealTimeScouter/Hanium-PdfReport#1]
보고서의 날짜가 갱신이 안됨.

**Comment by occidere** [comment]
# 수정 전
![image](https://user-images.githubusercontent.com/20942871/29707814-9d0cb15c-89c1-11e7-856b-a7bf18d995d5.png)

# 수정 후
![image](https://user-images.githubusercontent.com/20942871/29709563-ba22bcea-89c7-11e7-8ac9-7056d8773738.png)
